server:
  port: 9528

# Spring
spring:
  application:
    # 应用名称
    name: nebula-gateway
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        username: nacos
        password: nacos
      config:
        # 配置中心地址
        username: nacos
        password: nacos
        context-path: /nacos
        # 配置文件格式
        file-extension: yml
  config:
    import:
      - application-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:redisson-application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

spring.cloud.sentinel:
  # 取消控制台懒加载
  eager: true
  transport:
    # 控制台地址
    dashboard: 127.0.0.1:8718
  # nacos配置持久化
  datasource:
    ds1:
      nacos:
        server-addr: 127.0.0.1:8848
        dataId: sentinel-gateway
        groupId: DEFAULT_GROUP
        data-type: json
        rule-type: flow

spring.cloud:
  gateway:
    default-filters:
      # 从请求中剥离的路径个数
      - StripPrefix=1
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    routes:
      - id: nebula-auth
        uri: lb://nebula-auth
        predicates:
          - Path=/auth/**
      - id: nebula-system
        uri: lb://nebula-system
        predicates:
          - Path=/system/**

knife4j:
  gateway:
    enabled: false
