spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.5.196:8488
        namespace: 38db37e5-01c7-4447-8e56-117f8b43c106 # dev 命名空间id
      config:
        # 配置中心地址
        server-addr: 47.103.5.196:8488
        namespace: 38db37e5-01c7-4447-8e56-117f8b43c106 # dev 命名空间id

spring.cloud.sentinel:
  transport:
    # 控制台地址
    dashboard: 47.103.5.196
    port: 8858
  # nacos配置持久化
  datasource:
    ds1:
      nacos:
        server-addr: 47.103.5.196:8488
        namespace: 38db37e5-01c7-4447-8e56-117f8b43c106 # dev 命名空间id
        username: nacos
        password: nacos
        dataId: sentinel-gateway
        groupId: DEFAULT_GROUP
        data-type: json
        rule-type: flow

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      # 开启
      enabled: true
      # 指定版本号(swagger2|openapi3)
      version: openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - nebula-gateway
